### ISSUE TITLE
Map canvas renders on only 50% of the width of the container!

### ISSUE THREAD

**Issue by zabeehkhan** [phegman/vue-mapbox-gl#11] opened 2017-09-14 09:04 UTC
I am trying MapBox with Vue 2 and I cannot make the map take the full width of the container. It only renders on 50% width of the container.

I have included the files in the head of my index.html as follows:
```
<script src='https://api.mapbox.com/mapbox-gl-js/v0.40.0/mapbox-gl.js'></script>
<link href='https://api.mapbox.com/mapbox-gl-js/v0.40.0/mapbox-gl.css' rel='stylesheet' />
```
I want the map in a component (Map.vue, I am using vue-router), so here is the code in Map.vue:

Script: 
`import Mapbox from 'mapbox-gl-vue';`

```
export default {
  components: {
     'mapbox': Mapbox
  }
}
```

Template:
```
    <mapbox access-token="pk.eyJ1Ijoic3BlZW5pY3Q....."
    :map-options="{
      style: 'mapbox://styles/mapbox/streets-v9',
      center: [-96, 37.8],
      zoom: 3
    }"
    :geolocate-control="{
      show: true, 
      position: 'top-left'
    }"
    :scale-control="{
      show: true,
      position: 'top-left'
    }"
    :fullscreen-control="{
      show: true,
      position: 'top-left'
    }">>
  </mapbox>
```

Style:
```
#map {
 width: 100%;
 height: 600px;
 position: absolute;
 margin:0;
 z-index:1;
}
```

I tried everything in the CSS id but it only renders the map in the right half of the width of the container, in the left one only the logo and the controls are displayed while the rest of the area is empty.

![screen shot 2017-09-14 at 1 33 21 pm](https://user-images.githubusercontent.com/26257446/30421218-5379ebb4-9951-11e7-8ae2-6677d1e087be.png)

**Comment by phegman** [comment] 2017-09-14 11:36
Hey Zabeeh,

I just tried to replicate the issue with the exact same settings but I wasn't able to replicate it. My guess is there is some conflicting css from somewhere else in your project. If you have a project staging link I happy to take a look.

If you haven't tried removing the `position: absolute` I would give that a try too.

Best,
Pete

**Comment by zabeehkhan** [comment] 2017-09-16 09:00
Hi phegman, 
I tried all your suggestions and that doesn't seem to be the issue here. 

I just tried things from scratch and the issue is still there. To replicate the issue in a brand new webpack-simple Vue.js project, I did the following:

```
$ vue init webpack-simple my-project
$ cd my-project
$ npm install
$ npm run dev
```
`npm install mapbox-gl-vue --save`

In my index.html's head section:
```
  <script src='https://api.mapbox.com/mapbox-gl-js/v0.40.0/mapbox-gl.js'></script>
  <link href='https://api.mapbox.com/mapbox-gl-js/v0.40.0/mapbox-gl.css' rel='stylesheet' />
```

In my main.js:
```
import Vue from 'vue'
import App from './App.vue'
import Mapbox from 'mapbox-gl-vue';

new Vue({
  el: '#app',
  components: {
    'mapbox': Mapbox
  },
  render: h => h(App)
})
```

In my App.vue:
```
<template>
  <div id="app">
    <mapbox access-token="pk.eyJ1Ijoic3BlZW5pY3QiLCJhIjoiY2o1NTJwZWx5MDdoOTMycDZ3ZTAwa2Q5OCJ9.MzaFUFdxfQ9BnabwKGj2Sg"
    :map-options="{
      style: 'mapbox://styles/mapbox/streets-v9',
      center: [-96, 37.8],
      zoom: 3
    }">
    </mapbox>
  </div>
</template>

<script>
import Mapbox from 'mapbox-gl-vue';
export default {
  name: 'app',
  components: {
    'mapbox': Mapbox
  },
  data () {
    return {
      msg: 'Welcome to Your Vue.js App'
    }
  }
}
</script>

<style>
#map {
  width: 100%;
  height: 500px;
}
</style>
```

And this gives me the exact same result as before: the map renders on only half the width. Can you please try this and see if you can replicate it?

Note: I had to import and register Mapbox again in the App.vue as the component obviously doesn't get registered globally through main.js.

**Comment by zabeehkhan** [comment] 2017-09-16 09:01
Hi phegman, 
I tried all your suggestions and that doesn't seem to be the issue here. 

I just tried things from scratch and the issue is still there. To replicate the issue in a brand new webpack-simple Vue.js project, I did the following:

```
$ vue init webpack-simple my-project
$ cd my-project
$ npm install
$ npm run dev
```
`npm install mapbox-gl-vue --save`

In my index.html's head section:
```
  <script src='https://api.mapbox.com/mapbox-gl-js/v0.40.0/mapbox-gl.js'></script>
  <link href='https://api.mapbox.com/mapbox-gl-js/v0.40.0/mapbox-gl.css' rel='stylesheet' />
```

In my main.js:
```
import Vue from 'vue'
import App from './App.vue'
import Mapbox from 'mapbox-gl-vue';

new Vue({
  el: '#app',
  components: {
    'mapbox': Mapbox
  },
  render: h => h(App)
})
```

In my App.vue:
```
<template>
  <div id="app">
    <mapbox access-token="pk.eyJ........."
    :map-options="{
      style: 'mapbox://styles/mapbox/streets-v9',
      center: [-96, 37.8],
      zoom: 3
    }">
    </mapbox>
  </div>
</template>

<script>
import Mapbox from 'mapbox-gl-vue';
export default {
  name: 'app',
  components: {
    'mapbox': Mapbox
  },
  data () {
    return {
      msg: 'Welcome to Your Vue.js App'
    }
  }
}
</script>

<style>
#map {
  width: 100%;
  height: 500px;
}
</style>
```

And this gives me the exact same result as before: the map renders on only half the width. Can you please try this and see if you can replicate it?

Note: I had to import and register Mapbox again in the App.vue as the component obviously doesn't get registered globally through main.js.

**Comment by phegman** [comment] 2017-09-16 13:02
Hey,

Thanks for the detailed steps, unfortunately I just followed those steps and still couldn't reproduce the issue. I did notice you don't need to do `import Mapbox from 'mapbox-gl-vue';` and ```  components: {
    'mapbox': Mapbox
  },``` 
in your main.js file, this can be done in just your App.vue file. But that didn't seem to be the issue. 

Here is the project I tested without issues: https://drive.google.com/file/d/0BwJ_lyHxOLl2ZHBlTnk1bGdicFk/view?usp=sharing

See if you have issues with the above (I deleted the node_modules folder so you will have to run `npm install`)

What browser were you testing in?

Best,
Pete

**Comment by zabeehkhan** [comment] 2017-09-16 13:23
Thank you for all the effort phegman, this one actually works fine! 

This seems like an issue with the webpack template I am using, because I copied everything over to my project and I still face the problem.

I will dig deeper into it and if I find anything worth posting, I would.

Thank you once again.

**Comment by phegman** [comment] 2017-09-17 00:42
Very weird, my guess is it may be an issue with how the CSS is getting parsed out of the .vue file. Webpack can be finicky depending on what environment you are on. You could always put the CSS in an external stylesheet or inline it. 

Closing this out for now, if you find out what the issue was please post here for others!

**Closed by phegman** 2017-09-17 00:42 UTC

**Comment by ryanpwaldon** [comment] 2017-09-21 11:52
Yeah, this looks to be related to the webpack template. Presuming you're still using the default styling, go into your App.vue file and disable ```text-align: center;``` on your ```#app``` element. Not sure why this works, but I stopped questioning a long time ago. Hope this helps!

**Comment by zabeehkhan** [comment] 2017-09-22 08:19
hey ryanpwaldon,
Thank you, it does work! Very weird though!

**Comment by 015988** [comment] 2018-02-27 14:55
ryanpwaldon's removal of "text-align: center" solved my problem with "pure" mapbox-gl-js/react as well.

**Comment by harmoose** [comment] 2018-08-06 16:07
In case it helps, rather than removing 'text-align: center' at a high level and affecting many elements, you can just set 'text-align: justify' on the Map element/component.

**Comment by matsad3547** [comment] 2018-10-31 02:06
Had the same problem with Mapbox in create react app - really bizarre that removing `textAlign: 'center'` fixed it!

**Comment by honkmother** [comment] 2019-04-08 23:09
lol @ this being a closed but unfixed issue by a large software company whose sole asset is their map widget

**Comment by louischausse** [comment] 2019-05-13 16:20
I have the same problem on a site built in React so I don't think the problem is strictly related to vue.js.

It seems that Mapbox styling includes some element.style that I can't overwrite. The position: absolute seems to be the problem. The same line of styling doesn't affect the other maps in my project.


<canvas class="mapboxgl-canvas" tabindex="0" aria-label="Map" width="311" height="450" style="position: absolute;width: 311px;height: 450px;"></canvas>

I made a video where you can clearly see the problem: https://share.vidyard.com/watch/vcRWxcnvVjTGidLmQCuJen

**Comment by raykudo** [comment] 2020-01-14 12:32
For those using Vue2 and struggling to show mapbox in full width on the modal

```
<template>
<button @click="openModal"></button-component>
<modal-component v-if="showModal" @close="closeModal"> // if you use v-show, modal width would be 50% somehow
.
.
<div slot="body">
  <div id="map"></div>
</div>
.
.
</modal-component>
<template>

<script>
methods: {
  createMap() {
    // map
    mapboxgl.accessToken = process.env.MIX_MAPBOX_TOKEN;
    var map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/mapbox/outdoors-v11',
    center: [-79.4512, 43.6568],
    zoom: 13
    });
    ...
  },
  openModal() {
    this.showModal = true;
    setTimeout(()=>{
      this.createMap();
    }),
  },
  closeModal() {
    this.showModal = false
  },
},
</script>
```

I use default modal component provided by doc https://vuejs.org/v2/examples/modal.html
